[project]
name = "LibraryLensAPI"
version = "0.1.0"
description = "Manage your film, series, and book collections with ease."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.4",
]
